on:
  push:
    branches: main

name: build

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # - name: Install Ubuntu dependencies
      #   run: |
      #     sudo apt-get install libgdal-dev
      #     sudo apt-get install libgeos-dev
      #     sudo apt-get install libproj-dev
      #     sudo apt-get install libudunits2-dev
      - name: Set up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            crosstalk
            DT
            glue
            htmltools
            leaflet
            librarian
            plotly
            reactlog
            shiny
            shinydashboard
            tidyverse
            readxl
            github::mitchelloharawild/icons

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book
          tinytex: true
          # uncomment below and fill to pin a version
          # version: 0.9.600

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
